### ISSUE TITLE
Update peerDependency to latest react-native

### ISSUE THREAD

**Issue by codler** [react-native-community/react-native-segmented-control#14]
npm WARN @react-native-community/segmented-control@1.0.2 requires a peer of react-native@^0.57.0 but none is installed. You must install peer dependencies yourself.

**Comment by Naturalclar** [comment]
Currently the peerDependency for this repo is `>= 0.57.0`, so as long as you have react-native installed that is newer than 0.57, there shouldn't be any warnings :)
