### ISSUE TITLE
"ld: 7 duplicate symbols for architecture x86_64"

### ISSUE THREAD

**Issue by codler** [react-native-community/react-native-segmented-control#15]
# Bug

Build fails when I try run `react-native run-ios`, this started to happen after I ran `pod install`

duplicate symbol _OBJC_IVAR_$_RCTSegmentedControl._selectedIndex in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControl.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControl.o)
duplicate symbol _OBJC_IVAR_$_RCTSegmentedControl._values in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControl.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControl.o)
duplicate symbol _OBJC_CLASS_$_RCTSegmentedControl in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControl.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControl.o)
duplicate symbol _OBJC_METACLASS_$_RCTSegmentedControl in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControl.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControl.o)
duplicate symbol _OBJC_IVAR_$_RCTSegmentedControl._onChange in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControl.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControl.o)
duplicate symbol _OBJC_CLASS_$_RCTSegmentedControlManager in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControlManager.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControlManager.o)
duplicate symbol _OBJC_METACLASS_$_RCTSegmentedControlManager in:
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTSegmentedControlManager.o)
    /Users/Grape/xcode/bolan/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/react-native-segmented-control/libreact-native-segmented-control.a(RCTSegmentedControlManager.o)
ld: 7 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

## Environment info

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 71.26 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5199772
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Library version: 1.0.2

**Comment by leonid-shevtsov** [comment]
:+1: same with RN 0.61, Xcode 11. Reverted to using the component packaged with RN. 

Is this library not ready to be used yet?

**Comment by fonov** [comment]
some issue workaround use `SegmentedControlIOS` from `react-native`

**Comment by bpdarlyn** [comment]
same issues react native 0.60.5

**Comment by GhayoorUlHaq** [comment]
Actually in RN 0.6x, some of libraries have different ways to install. Some of libraries only need `react-native link` to link both iOS and Android but some of libraries need `pod install` for iOS as well. In case you need just `react-native link` for both and you'll run `pod install`, duplicate symbol error will appear. You can check _react-native-vector-icons_ library, same thing happens to this. It only require `react-native link` to link both iOS and Android or you have to manually link both otherwise same error will appear.

**Comment by matt-oakes** [comment]
The issue is that the library file names are clashing with the built-in ones. To fix this, the iOS file prefixes need to be renamed from `RTC` to something like `RNC`.
