### ISSUE TITLE
iOS 13 SegmentedControl support

### ISSUE THREAD

**Issue by Guap6512** [react-native-community/react-native-segmented-control#16]
Library version: 1.0.2

iOS 13 introduced a new version of SegmentedControl with changes in API, and library does not support customizing it now. Every SegmentedControl made with it now looks like this:
![image](https://user-images.githubusercontent.com/4889644/65751050-c90d4480-e11a-11e9-9221-ccee78261cea.png)

**tintColor** property makes no effect on it's appearance anymore.

**Comment by funkyyy** [comment]
same prob with ios13 what to do now? any idea?

**Comment by emirvajzovic** [comment]
**segmentedControl.selectedSegmentTintColor = .clear** for iOS 13

**Comment by emirvajzovic** [comment]
segmentedControl.selectedSegmentTintColor = .clear
Only works on iOS 13.

**Comment by VenomApps** [comment]
What's the status on this! Nothing is working!

**Comment by ferrannp** [comment]
It looks like this component needs a re-work with all the new properties that iOS 13 brings to SegmentedControl. As you said, you are right, `tintColor` won't work anymore.

**Comment by cpojer** [comment]
@ferrannp is it possible that these were fixed in the version on react native master since we haven't actually removed that component from RN yet (we were waiting for stable releases).

**Comment by radko93** [comment]
@cpojer I don't see `tintColor` fixed on RN 0.61.2 on iOS 13.

**Comment by cpojer** [comment]
Here is a fix by @sammy-SC:

```
- (void)setTintColor:(UIColor *)tintColor
{
  [super setTintColor:tintColor];
  if (@available(iOS 13.0, *)) {
    [self setSelectedSegmentTintColor:tintColor];
    [self setTitleTextAttributes:@{NSForegroundColorAttributeName: [UIColor whiteColor]}
                        forState:UIControlStateSelected];
    [self setTitleTextAttributes:@{NSForegroundColorAttributeName: tintColor}
                        forState:UIControlStateNormal];
  }
}

```

**Comment by cpojer** [comment]
It has to go into the module here as a PR: https://github.com/react-native-community/react-native-segmented-control/blob/master/ios/RCTSegmentedControl.m

**Comment by ferrannp** [comment]
There are more stuff we can do to [UISegmentedControl ](https://developer.apple.com/documentation/uikit/uisegmentedcontrol) right now with iOS 13 @cpojer. I think it would be good to update it here and remove it from core (now core is fixed, here is not). @harisbaig100 are you around?

**Comment by cpojer** [comment]
@ferrannp We'll remove it from RN soon!

**Comment by ferrannp** [comment]
@cpojer thank you but we would probably need a new maintainer here :)

**Comment by errawn** [comment]
ff

**Comment by Naturalclar** [comment]
@cpojer @ferrannp 
If it's not a problem, I'd like to help maintain this package.
Is there anything I can do to help?
