### ISSUE TITLE
Installing this package following the docs leads to an installation of a fork of this package

### ISSUE THREAD

**Issue by nacho-carnicero** [react-native-community/react-native-segmented-control#37]
# Bug

This has nothing to do with the package itself but with the docs, specifically the docs for installing this package.

Indeed, in the docs, it is stated that in order to install this package you should do:

```
yarn add @react-native-community/segmented-control
```

or its equivalent for users using `npm`.

Now the huge problem is that by doing that users are actually installing [this fork](https://github.com/harisbaig100/react-native-segmented-control) of the project since the [npm package](https://www.npmjs.com/package/@react-native-community/segmented-control) redirects to that page.

The end-user will not necessarily notice since the installed package contains a segment control component with the same API, but this, in my opinion, is very bad because:
 * fixes and new features in the current package won't be applied to the package that users are installing
 * it opens the door for harmful code being installed

## Steps To Reproduce

1. `yarn add @react-native-community/segmented-control`
2. Check the `package.json` file of the installed package in the `node_modules` folder and see that the home page is `https://github.com/harisbaig100/react-native-segmented-control#readme`

Describe what you expected to happen:

1. `yarn add @react-native-community/segmented-control` installs code from this repository as it is stated in the docs

**Comment by Naturalclar** [comment]
@nacho-carnicero Thanks for opening an issue!
I'm currently working on iOS 13 support of this repo, and I will publish the package from the react-native-community org :)

**Comment by Naturalclar** [comment]
@nacho-carnicero Just published v1.1.0 from this repository :)

**Comment by nacho-carnicero** [comment]
Awesome @Naturalclar thank you!
